module.exports = [
  {
    slug: 'fog-harbor-letter',
    title: '雾港来信',
    gameType: '剧本杀',
    tags: ['情感', '沉浸', '新手友好'],
    difficulty: '入门',
    durationMin: 180,
    minPlayers: 6,
    maxPlayers: 6,
    highlights: ['人物关系清晰', '情感线循序渐进', '适合第一次尝试'],
    warnings: ['包含离别主题', '不适合只想纯推理的玩家'],
    description: '一封迟到多年的信，把几位旧友重新带回雾港。',
  },
  {
    slug: 'silent-mansion',
    title: '静默公馆',
    gameType: '剧本杀',
    tags: ['硬核推理', '推理', '沉浸'],
    difficulty: '进阶',
    durationMin: 240,
    minPlayers: 6,
    maxPlayers: 7,
    highlights: ['线索密度高', '时间线严谨', '适合复盘'],
    warnings: ['信息量较大', '需要完整投入四小时'],
    description: '暴雪封山后，公馆中的每个人都在隐瞒一段时间。',
  },
  {
    slug: 'midnight-train',
    title: '午夜列车',
    gameType: '剧本杀',
    tags: ['恐怖', '沉浸', '机制'],
    difficulty: '进阶',
    durationMin: 210,
    minPlayers: 6,
    maxPlayers: 7,
    highlights: ['氛围演绎强', '机制与剧情交错', '节奏紧凑'],
    warnings: ['含惊吓和压迫感桥段', '怕黑或怕惊吓请谨慎'],
    description: '驶向终点的列车没有下一站，乘客却一个个收到同一张车票。',
  },
  {
    slug: 'red-moon-camp',
    title: '红月营地',
    gameType: '狼人杀',
    tags: ['机制', '阵营', '竞技', '新手友好'],
    difficulty: '入门',
    durationMin: 120,
    minPlayers: 8,
    maxPlayers: 12,
    highlights: ['规则易懂', '发言节奏快', '适合新手教学'],
    warnings: ['对抗感明显', '不喜欢公开发言请谨慎'],
    description: '红月升起后的营地里，所有人都要在有限信息中做出选择。',
  },
  {
    slug: 'clocktower-first-light',
    title: '钟楼初响',
    gameType: '血染钟楼',
    tags: ['阵营', '推理', '社交', '新手友好'],
    difficulty: '入门',
    durationMin: 150,
    minPlayers: 8,
    maxPlayers: 12,
    highlights: ['角色能力丰富', '允许出局后继续参与', '适合社交局'],
    warnings: ['需要主持人带领流程', '信息交换较频繁'],
    description: '钟声响起后，村庄里的每个人都拥有一条可能改变结局的信息。',
  },
  {
    slug: 'small-town-stories',
    title: '小镇物语',
    gameType: '桌游',
    tags: ['轻松', '合作', '社交', '新手友好'],
    difficulty: '入门',
    durationMin: 75,
    minPlayers: 2,
    maxPlayers: 4,
    highlights: ['规则负担低', '合作目标明确', '适合熟人和新手'],
    warnings: ['策略深度较轻', '喜欢强对抗的玩家可能觉得简单'],
    description: '一起经营一座小镇，在有限回合里完成居民们的愿望。',
  },
  {
    slug: 'deep-space-route',
    title: '深空航线',
    gameType: '桌游',
    tags: ['机制', '竞技', '策略'],
    difficulty: '进阶',
    durationMin: 120,
    minPlayers: 3,
    maxPlayers: 5,
    highlights: ['资源规划有层次', '每局路线不同', '适合喜欢研究机制'],
    warnings: ['首局学习成本较高', '不建议中途加入'],
    description: '船员们要在燃料耗尽前规划一条最有价值的深空航线。',
  },
  {
    slug: 'green-valley-rpg',
    title: '绿谷来客',
    gameType: '跑团',
    tags: ['轻松', '合作', '沉浸', '新手友好'],
    difficulty: '入门',
    durationMin: 180,
    minPlayers: 3,
    maxPlayers: 5,
    highlights: ['角色目标清晰', 'GM 可快速带入', '适合短团体验'],
    warnings: ['需要连续投入三小时', '偏好纯战斗的玩家可能不适应'],
    description: '一支临时组成的队伍，在绿谷边缘寻找失踪的商队。',
  },
];
